In [1]:
import numpy as np

In [2]:
# Letra a
# Leia o arquivo array.dat usando o comando np.loadtxt() e armazene o mesmo como “array_original”
array_original = np.loadtxt("array.dat")
array_original

array([[ 11.,   6.,  -3.,   5.,   9., -10.,   0.,   1.,  -7.,  -6.,   6.,
          4.,  11.,  -8.,  -9.,   6.,  -4.,   2.,   1.,  10.],
       [  5.,   3.,  -1.,   0.,  -9.,  -6.,  -4.,  -6.,   1.,  10.,   5.,
          5.,   1.,   1.,  11.,   6.,   8.,  -1.,   3.,  10.],
       [  9.,   3.,   5.,  11.,  11.,  11.,   3.,   6.,   2.,   7.,  11.,
          8.,  -3.,   2.,  -9.,   7., -10.,  10.,   2.,  -1.],
       [  0.,  -1.,  -7.,  -8.,  -5.,  -3.,   9.,   2.,   7.,   4.,  11.,
         -7.,  10.,   0.,   1.,   2.,  10.,   8.,   1.,  -8.],
       [ -3.,   3.,  -8.,  -4.,   6.,   9.,  -4.,  -2.,  -7.,  -1.,  -9.,
         -5.,  -9.,  -3.,  -7.,  -5.,  -6.,  11., -10.,   2.],
       [  5.,  -6.,  -2.,   0.,   2.,  -8.,  -3.,  -7.,   7.,  -2.,  -2.,
         -4.,  -3.,  -1.,   8.,  10.,   4.,  -2.,  -3.,   2.]])

In [3]:
# Letra b
# Defina um novo array como sendo igual a 3a coluna do array_original, e um outro array como sendo a 5a linha do array_original.
novo_array = array_original[:,2]
outro_array = array_original[4]

print("Array igual a 3a coluna ",novo_array)
print("\n Array igual a 5 linha ", outro_array)

Array igual a 3a coluna  [-3. -1.  5. -7. -8. -2.]

 Array igual a 5 linha  [ -3.   3.  -8.  -4.   6.   9.  -4.  -2.  -7.  -1.  -9.  -5.  -9.  -3.
  -7.  -5.  -6.  11. -10.   2.]


In [4]:
# Letra c
# Defina um novo array com com as colunas pares do array_ogirinal
colunas_pares = array_original[:,1::2]
colunas_pares

array([[  6.,   5., -10.,   1.,  -6.,   4.,  -8.,   6.,   2.,  10.],
       [  3.,   0.,  -6.,  -6.,  10.,   5.,   1.,   6.,  -1.,  10.],
       [  3.,  11.,  11.,   6.,   7.,   8.,   2.,   7.,  10.,  -1.],
       [ -1.,  -8.,  -3.,   2.,   4.,  -7.,   0.,   2.,   8.,  -8.],
       [  3.,  -4.,   9.,  -2.,  -1.,  -5.,  -3.,  -5.,  11.,   2.],
       [ -6.,   0.,  -8.,  -7.,  -2.,  -4.,  -1.,  10.,  -2.,   2.]])

In [5]:
# Letra d
# Defina um novo array com as linhas impares do array_original
linhas_impares = array_original[0::2]
linhas_impares

array([[ 11.,   6.,  -3.,   5.,   9., -10.,   0.,   1.,  -7.,  -6.,   6.,
          4.,  11.,  -8.,  -9.,   6.,  -4.,   2.,   1.,  10.],
       [  9.,   3.,   5.,  11.,  11.,  11.,   3.,   6.,   2.,   7.,  11.,
          8.,  -3.,   2.,  -9.,   7., -10.,  10.,   2.,  -1.],
       [ -3.,   3.,  -8.,  -4.,   6.,   9.,  -4.,  -2.,  -7.,  -1.,  -9.,
         -5.,  -9.,  -3.,  -7.,  -5.,  -6.,  11., -10.,   2.]])

In [6]:
# Letra e
# Defina um novo array com os números múltiplos de 5 do array_original.
multiplos_5 = array_original[array_original%5==0];
multiplos_5

array([  5., -10.,   0.,  10.,   5.,   0.,  10.,   5.,   5.,  10.,   5.,
       -10.,  10.,   0.,  -5.,  10.,   0.,  10.,  -5.,  -5., -10.,   5.,
         0.,  10.])

In [7]:
# Letra f
# Defina um array com apenas os números positivos do array_original.
maior_5 = array_original[array_original > 0]
maior_5

array([11.,  6.,  5.,  9.,  1.,  6.,  4., 11.,  6.,  2.,  1., 10.,  5.,
        3.,  1., 10.,  5.,  5.,  1.,  1., 11.,  6.,  8.,  3., 10.,  9.,
        3.,  5., 11., 11., 11.,  3.,  6.,  2.,  7., 11.,  8.,  2.,  7.,
       10.,  2.,  9.,  2.,  7.,  4., 11., 10.,  1.,  2., 10.,  8.,  1.,
        3.,  6.,  9., 11.,  2.,  5.,  2.,  7.,  8., 10.,  4.,  2.])

In [8]:
# Letra g
# Defina um novo array como sendo a transposta do array_original
transposta = np.transpose(array_original)

transposta

array([[ 11.,   5.,   9.,   0.,  -3.,   5.],
       [  6.,   3.,   3.,  -1.,   3.,  -6.],
       [ -3.,  -1.,   5.,  -7.,  -8.,  -2.],
       [  5.,   0.,  11.,  -8.,  -4.,   0.],
       [  9.,  -9.,  11.,  -5.,   6.,   2.],
       [-10.,  -6.,  11.,  -3.,   9.,  -8.],
       [  0.,  -4.,   3.,   9.,  -4.,  -3.],
       [  1.,  -6.,   6.,   2.,  -2.,  -7.],
       [ -7.,   1.,   2.,   7.,  -7.,   7.],
       [ -6.,  10.,   7.,   4.,  -1.,  -2.],
       [  6.,   5.,  11.,  11.,  -9.,  -2.],
       [  4.,   5.,   8.,  -7.,  -5.,  -4.],
       [ 11.,   1.,  -3.,  10.,  -9.,  -3.],
       [ -8.,   1.,   2.,   0.,  -3.,  -1.],
       [ -9.,  11.,  -9.,   1.,  -7.,   8.],
       [  6.,   6.,   7.,   2.,  -5.,  10.],
       [ -4.,   8., -10.,  10.,  -6.,   4.],
       [  2.,  -1.,  10.,   8.,  11.,  -2.],
       [  1.,   3.,   2.,   1., -10.,  -3.],
       [ 10.,  10.,  -1.,  -8.,   2.,   2.]])

In [13]:
# Letra h
# Defina um novo array como sendo um array achatado (apenas uma linha) do array_original usando reshape , ravel ou flatten 
# (olhe na documentação do numpy imbutida nos links anteriores)
achatado = array_original.flatten()

achatado


array([ 11.,   6.,  -3.,   5.,   9., -10.,   0.,   1.,  -7.,  -6.,   6.,
         4.,  11.,  -8.,  -9.,   6.,  -4.,   2.,   1.,  10.,   5.,   3.,
        -1.,   0.,  -9.,  -6.,  -4.,  -6.,   1.,  10.,   5.,   5.,   1.,
         1.,  11.,   6.,   8.,  -1.,   3.,  10.,   9.,   3.,   5.,  11.,
        11.,  11.,   3.,   6.,   2.,   7.,  11.,   8.,  -3.,   2.,  -9.,
         7., -10.,  10.,   2.,  -1.,   0.,  -1.,  -7.,  -8.,  -5.,  -3.,
         9.,   2.,   7.,   4.,  11.,  -7.,  10.,   0.,   1.,   2.,  10.,
         8.,   1.,  -8.,  -3.,   3.,  -8.,  -4.,   6.,   9.,  -4.,  -2.,
        -7.,  -1.,  -9.,  -5.,  -9.,  -3.,  -7.,  -5.,  -6.,  11., -10.,
         2.,   5.,  -6.,  -2.,   0.,   2.,  -8.,  -3.,  -7.,   7.,  -2.,
        -2.,  -4.,  -3.,  -1.,   8.,  10.,   4.,  -2.,  -3.,   2.])

In [15]:
# Letra i
# Utilizando reshape sobre o array do item anterior, gere um array final com 12 linhas e 10 colunas
reshape = np.reshape(array_original, (12,10))
reshape

array([[ 11.,   6.,  -3.,   5.,   9., -10.,   0.,   1.,  -7.,  -6.],
       [  6.,   4.,  11.,  -8.,  -9.,   6.,  -4.,   2.,   1.,  10.],
       [  5.,   3.,  -1.,   0.,  -9.,  -6.,  -4.,  -6.,   1.,  10.],
       [  5.,   5.,   1.,   1.,  11.,   6.,   8.,  -1.,   3.,  10.],
       [  9.,   3.,   5.,  11.,  11.,  11.,   3.,   6.,   2.,   7.],
       [ 11.,   8.,  -3.,   2.,  -9.,   7., -10.,  10.,   2.,  -1.],
       [  0.,  -1.,  -7.,  -8.,  -5.,  -3.,   9.,   2.,   7.,   4.],
       [ 11.,  -7.,  10.,   0.,   1.,   2.,  10.,   8.,   1.,  -8.],
       [ -3.,   3.,  -8.,  -4.,   6.,   9.,  -4.,  -2.,  -7.,  -1.],
       [ -9.,  -5.,  -9.,  -3.,  -7.,  -5.,  -6.,  11., -10.,   2.],
       [  5.,  -6.,  -2.,   0.,   2.,  -8.,  -3.,  -7.,   7.,  -2.],
       [ -2.,  -4.,  -3.,  -1.,   8.,  10.,   4.,  -2.,  -3.,   2.]])